version: 2
jobs:
    build:

        working_directory: ~/java-circleci-poc

        docker:
            - image: circleci/openjdk:8

        steps:
            - checkout

            - run:
                name: Compute pom checksum for cache
                command: |
                    find . -maxdepth 2 -type f -name "pom.xml" -exec cat {} \; > all-poms.xml

            - restore_cache:
                key: java-circleci-poc-{{ checksum "all-poms.xml" }}

            - run:
                name: Run build of code
                command: ./build

            - save_cache:
                paths:
                    - ~/.m2
                key: java-circleci-poc-{{ checksum "all-poms.xml" }}

    deploy:

        working_directory: ~/java-circleci-poc

        docker:
            - image: circleci/openjdk:8

        steps:
            - run:
                name: Do a thing
                command: echo "Howdy"

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
                    tags:
                        only: /^v.*/

